export const CITYWISE_EVENT_MOCK: any[] = [
    {
        name: 'This is an Physical Event',
        dateTimeStr: 'Jan 22 | 4PM',
        eventType: 'physical',
        venue: 'City Center II',
        city: 'Kolkata',
        priceDisplayStr: '₹500 Onwards',
    },
    {
        name: 'This is an Physical Event',
        dateTimeStr: 'Jan 22 | 4PM',
        eventType: 'physical',
        venue: 'City Center II',
        city: 'Kolkata',
        priceDisplayStr: '₹500 Onwards',
    },
    {
        name: 'This is an Physical Event',
        dateTimeStr: 'Jan 22 | 4PM',
        eventType: 'physical',
        venue: 'City Center II',
        city: 'Kolkata',
        priceDisplayStr: '₹500 Onwards',
    },
    {
        name: 'This is an Physical Event',
        dateTimeStr: 'Jan 22 | 4PM',
        eventType: 'physical',
        venue: 'City Center II',
        city: 'Kolkata',
        priceDisplayStr: '₹500 Onwards',
    },
    {
        name: 'This is an Physical Event',
        dateTimeStr: 'Jan 22 | 4PM',
        eventType: 'physical',
        venue: 'City Center II',
        city: 'Kolkata',
        priceDisplayStr: '₹500 Onwards',
    },
    {
        name: 'This is an Physical Event',
        dateTimeStr: 'Jan 22 | 4PM',
        eventType: 'physical',
        venue: 'City Center II',
        city: 'Kolkata',
        priceDisplayStr: '₹500 Onwards',
    },
    {
        name: 'This is an Physical Event',
        dateTimeStr: 'Jan 22 | 4PM',
        eventType: 'physical',
        venue: 'City Center II',
        city: 'Kolkata',
        priceDisplayStr: '₹500 Onwards',
    },
    {
        name: 'This is an Physical Event',
        dateTimeStr: 'Jan 22 | 4PM',
        eventType: 'physical',
        venue: 'City Center II',
        city: 'Kolkata',
        priceDisplayStr: '₹500 Onwards',
    },
]